version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Pokemon_Node_App

hooks:
  BeforeInstall:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/app_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: ec2-user
